import { config } from "./config.js";
const keys=[];const health=new Map();let cursor=0;
const normalizeKey=k=>String(k||"").trim().replace(/^["']|["']$/g,"");
const isValidKey=k=>{const s=normalizeKey(k);return s.length>=20&&/^(sk-|sk-xt-)/i.test(s);};
export function maskKey(k){const s=normalizeKey(k);return s.length<12?"***":`${s.slice(0,7)}…${s.slice(-4)}`;}
function uniquePush(k){const s=normalizeKey(k);if(!isValidKey(s))return{ok:false,reason:"key không hợp lệ (cần sk- / sk-xt- …)"};if(keys.includes(s))return{ok:false,reason:"key đã có trong pool",key:s,masked:maskKey(s)};keys.unshift(s);cursor=0;return{ok:true,key:s,masked:maskKey(s),index:0};}
export function initKeyPool(){keys.length=0;health.clear();cursor=0;const fromList=(process.env.AI_API_KEYS||"").split(/[\s,;]+/).map(normalizeKey).filter(Boolean);for(const k of [config.ai.apiKey,...fromList].filter(Boolean))uniquePush(k);if(!keys.length)throw new Error("Không có AI API key nào (AI_API_KEY / AI_API_KEYS)");cursor=0;console.log(`[keys] pool = ${keys.length} key(s), newest-first: ${keys.map(maskKey).join(", ")}`);return keys.length;}
function stateOf(k){const s=health.get(k);if(!s)return null;if(s.until!==Infinity&&s.until<=Date.now()){health.delete(k);return null;}return s;}
export function getKeyCount(){return keys.length;}
export function getHealthyKeyCount(){return keys.filter(k=>!stateOf(k)).length;}
export function listKeysMasked(){return keys.map((k,i)=>{const s=stateOf(k);return{index:i,masked:maskKey(k),status:s?(s.until===Infinity?`disabled: ${s.reason}`:`cooldown ${Math.ceil((s.until-Date.now())/1000)}s: ${s.reason}`):"healthy"};});}
export function getCurrentKey(){return acquireKey();}
export function acquireKey(exclude=[]){if(!keys.length)throw new Error("pool key rỗng");const blocked=new Set(exclude);for(let n=0;n<keys.length;n++){const i=(cursor+n)%keys.length,k=keys[i];if(!blocked.has(k)&&!stateOf(k)){cursor=(i+1)%keys.length;return k;}}for(let n=0;n<keys.length;n++){const i=(cursor+n)%keys.length,k=keys[i];if(!stateOf(k)){cursor=(i+1)%keys.length;return k;}}throw new Error("Tất cả API key đang lỗi hoặc cooldown. Dùng `.api list` để xem trạng thái.");}
export function reportKeySuccess(key){if(health.has(key)){health.delete(key);console.log(`[keys] healthy again ${maskKey(key)}`);}}
export function reportKeyFailure(key,err){const status=err?.status||err?.response?.status||err?.statusCode;const msg=String(err?.message||err||"").toLowerCase();let until=0,reason="";if(status===401||/invalid or disabled clientapikey|invalid.*key|incorrect.*key|unauthorized/.test(msg)){until=Infinity;reason="401 invalid/disabled";}else if(status===402||/insufficient|balance|credit/.test(msg)){until=Date.now()+12*60*60_000;reason="hết credit";}else if(status===429||/quota|rate limit|too many/.test(msg)){const daily=/today|daily|free-model token quota/.test(msg);until=Date.now()+(daily?8*60*60_000:2*60_000);reason=daily?"hết quota ngày":"rate limit";}else if(/timed?\s*out|timeout/.test(msg)){until=Date.now()+15_000;reason="timeout";}if(until){health.set(key,{until,reason,at:Date.now()});console.warn(`[keys] quarantine ${maskKey(key)} ${reason}${until===Infinity?"":` ${Math.ceil((until-Date.now())/1000)}s`}`);return true;}return false;}
export function rotateKey(reason=""){const key=acquireKey();console.log(`[keys] next ${maskKey(key)}${reason?` (${reason})`:""}`);return key;}
export function addKeys(input){const parts=String(input||"").split(/[\s,;]+/).map(normalizeKey).filter(Boolean),added=[],skipped=[];for(const p of parts){const r=uniquePush(p);if(r.ok)added.push(r.masked);else skipped.push({masked:isValidKey(p)?maskKey(p):p.slice(0,12),reason:r.reason});}return{added,skipped,total:keys.length};}
export function removeKey(query){const q=String(query||"").trim();if(!q)return{ok:false,reason:"thiếu index hoặc đuôi key"};let idx=/^\d+$/.test(q)?Number(q):keys.findIndex(k=>k.endsWith(q)||maskKey(k).includes(q)||k.includes(q));if(idx<0||idx>=keys.length)return{ok:false,reason:"không tìm thấy key"};if(keys.length<=1)return{ok:false,reason:"phải giữ ít nhất 1 key"};const key=keys[idx],removed=maskKey(key);keys.splice(idx,1);health.delete(key);if(cursor>=keys.length)cursor=0;return{ok:true,removed,total:keys.length};}
export function shouldRotateOnError(err){const status=err?.status||err?.response?.status||err?.statusCode,msg=String(err?.message||err||"").toLowerCase();return[401,402,403,409,429].includes(status)||/invalid.*key|unauthorized|forbidden|quota|insufficient|balance|credit|rate limit|too many|duplicate request|already being processed/i.test(msg);}